<#
.SYNOPSIS
Project Shorebird entry point. Release and patch validate without publishing unless -Publish is supplied.
.EXAMPLE
./tool/shorebird/shorebird.ps1 patch -ReleaseVersion '3.8.3+235' -DryRun
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateSet('init', 'doctor', 'release', 'patch', 'preview')]
    [string]$Command,
    [ValidateSet('android', 'ios')]
    [string]$Platform = 'android',
    [ValidateSet('aab', 'apk')]
    [string]$Artifact = 'aab',
    [string]$ReleaseVersion,
    [ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')]
    [string]$Track = 'staging',
    [string]$DeviceId,
    [string[]]$FlutterArgs = @(),
    [switch]$Publish,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$isWindowsHost = [Environment]::OSVersion.Platform -eq 'Win32NT'
$androidTargets = 'android-arm64,android-x64'

function Resolve-Shorebird {
    $installationRoot = $env:OPENIM_SHOREBIRD_DIR
    if (!$installationRoot -and $isWindowsHost) {
        $installationRoot = [Environment]::GetEnvironmentVariable('OPENIM_SHOREBIRD_DIR', 'User')
    }
    if ($installationRoot) {
        $cliBin = Join-Path $installationRoot 'bin'
        $candidate = Join-Path $cliBin $(if ($isWindowsHost) { 'shorebird.ps1' } else { 'shorebird' })
        if (!(Test-Path -LiteralPath $candidate -PathType Leaf)) {
            throw "Shorebird CLI not found at $candidate. OPENIM_SHOREBIRD_DIR must be its installation root."
        }
        return [IO.Path]::GetFullPath($candidate)
    }
    $cli = Get-Command shorebird -CommandType Application, ExternalScript -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($cli) {
        # The official Windows .bat entry point forwards only nine arguments.
        # Prefer its sibling .ps1 to preserve the complete argument array.
        $powershellEntry = Join-Path (Split-Path $cli.Source) 'shorebird.ps1'
        if ($isWindowsHost -and (Test-Path -LiteralPath $powershellEntry -PathType Leaf)) {
            return $powershellEntry
        }
        return $cli.Source
    }
    if ($DryRun) { return 'shorebird' }
    throw 'Shorebird CLI is missing. Add its bin directory to PATH or set OPENIM_SHOREBIRD_DIR.'
}

function Assert-ShorebirdConfig {
    $configPath = Join-Path $projectRoot 'shorebird.yaml'
    if (!(Test-Path -LiteralPath $configPath -PathType Leaf)) {
        throw 'shorebird.yaml is missing. Sign in with shorebird login, then run this script with init.'
    }
    $config = Get-Content -LiteralPath $configPath -Raw
    $uuidPattern = '(?im)^app_id:\s*[''"]?([0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12})[''"]?\s*(?:#.*)?$'
    if ($config -notmatch $uuidPattern -or $Matches[1] -eq '00000000-0000-0000-0000-000000000000') {
        throw 'shorebird.yaml has no valid app_id. Use the real ID generated by authenticated shorebird init.'
    }
    if ($config -match '(?im)^auto_update:\s*false\s*(?:#.*)?$') {
        throw 'auto_update:false disables the built-in updater. This project requires auto_update:true (or the default).'
    }
    $pubspec = Get-Content -LiteralPath (Join-Path $projectRoot 'pubspec.yaml') -Raw
    if ($pubspec -notmatch '(?m)^\s*-\s*[''"]?shorebird\.yaml[''"]?\s*(?:#.*)?$') {
        throw 'pubspec.yaml must include shorebird.yaml in flutter.assets. Review the changes generated by shorebird init.'
    }
}

if ($Publish -and $Command -notin @('release', 'patch')) {
    throw '-Publish applies only to release and patch.'
}
if ($ReleaseVersion -and $Command -notin @('patch', 'preview')) {
    throw '-ReleaseVersion applies only to patch and preview. A release uses the project build version.'
}
if ($DeviceId -and $Command -ne 'preview') {
    throw '-DeviceId applies only to preview.'
}
if ($PSBoundParameters.ContainsKey('Artifact') -and ($Command -ne 'release' -or $Platform -ne 'android')) {
    throw '-Artifact applies only to Android release.'
}
if ($PSBoundParameters.ContainsKey('Track') -and $Command -notin @('patch', 'preview')) {
    throw '-Track applies only to patch and preview.'
}
if ($Command -in @('patch', 'preview')) {
    if ($ReleaseVersion -notmatch '^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?\+\d+$') {
        throw 'Specify an exact base -ReleaseVersion such as 3.8.3+235. latest and inferred versions are not allowed.'
    }
}
if ($FlutterArgs.Count -gt 0 -and $Command -notin @('release', 'patch')) {
    throw '-FlutterArgs applies only to release and patch.'
}
if ($FlutterArgs | Where-Object { $_ -match '^--(?:target-platform|flutter-version)(?:=|$)' }) {
    throw 'Flutter version and Android target platforms are controlled by this project entry point.'
}
if ($Platform -eq 'ios' -and $Command -in @('release', 'patch', 'preview') -and $isWindowsHost -and !$DryRun) {
    throw 'iOS release, patch and preview require macOS with Xcode. See README.md for direct CLI commands.'
}

$cliArguments = @($Command)
switch ($Command) {
    'init' {
        if (!$DryRun -and (Test-Path -LiteralPath (Join-Path $projectRoot 'shorebird.yaml'))) {
            throw 'shorebird.yaml already exists. Review its registered app before running init again.'
        }
    }
    'release' {
        $flutterVersion = (Get-Content -LiteralPath (Join-Path $projectRoot '.flutter-version') -Raw).Trim()
        if ($flutterVersion -notmatch '^\d+\.\d+\.\d+$') {
            throw '.flutter-version must contain an explicit Flutter version.'
        }
        $cliArguments += @($Platform, "--flutter-version=$flutterVersion")
        if ($Platform -eq 'android') {
            $cliArguments += @("--artifact=$Artifact", "--target-platform=$androidTargets")
        }
        if (!$Publish) { $cliArguments += '--dry-run' }
    }
    'patch' {
        $cliArguments += @($Platform, "--release-version=$ReleaseVersion", "--track=$Track")
        if (!$Publish) { $cliArguments += '--dry-run' }
    }
    'preview' {
        $cliArguments += @("--platform=$Platform", "--release-version=$ReleaseVersion", "--track=$Track")
        if ($DeviceId) { $cliArguments += "--device-id=$DeviceId" }
    }
}
if ($Command -eq 'patch' -and $Platform -eq 'android') {
    # Patch uses the base release's Flutter revision; its parser does not expose
    # target-platform, so this ABI restriction must be forwarded to Flutter.
    $cliArguments += @('--', "--target-platform=$androidTargets") + $FlutterArgs
} elseif ($FlutterArgs.Count -gt 0) {
    $cliArguments += @('--') + $FlutterArgs
}

if ($Command -in @('release', 'patch', 'preview')) {
    if ($DryRun) {
        Write-Host 'Argument preview only. Configuration, authentication and build readiness are not verified.'
    } else {
        Assert-ShorebirdConfig
    }
}
$shorebirdCli = Resolve-Shorebird
if ($DryRun) {
    Write-Output ([ordered]@{ workingDirectory = $projectRoot; cli = $shorebirdCli; arguments = $cliArguments } | ConvertTo-Json -Depth 3)
    return
}
if ($Command -in @('release', 'patch')) {
    if ($Publish) {
        Write-Host "Publishing $Command to Shorebird. Review the app, release version and track before invoking -Publish."
    } else {
        Write-Host 'Build validation only (--dry-run). No release or patch will be uploaded.'
    }
}
if ($Command -eq 'preview' -and $Platform -eq 'android') {
    Write-Host 'Preview reinstalls the app and clears its local data. Use a test device and test account.'
}
$savedGitEnvironment = $null
Push-Location $projectRoot
try {
    if ($isWindowsHost) {
        # Shorebird clones historical Flutter revisions whose paths can exceed
        # Windows Git's default limit. Append a process-only override so all
        # child Git commands inherit it without changing user/system config.
        $countName = 'GIT_CONFIG_COUNT'
        $previousCount = [Environment]::GetEnvironmentVariable($countName, 'Process')
        [int]$configCount = 0
        if ($null -ne $previousCount -and
            (![int]::TryParse($previousCount, [ref]$configCount) -or
                $configCount -lt 0 -or $configCount -eq [int]::MaxValue)) {
            throw 'GIT_CONFIG_COUNT must be a non-negative integer before invoking Shorebird.'
        }
        $keyName = "GIT_CONFIG_KEY_$configCount"
        $valueName = "GIT_CONFIG_VALUE_$configCount"
        $savedGitEnvironment = [ordered]@{
            $countName = $previousCount
            $keyName = [Environment]::GetEnvironmentVariable($keyName, 'Process')
            $valueName = [Environment]::GetEnvironmentVariable($valueName, 'Process')
        }
        [Environment]::SetEnvironmentVariable($keyName, 'core.longpaths', 'Process')
        [Environment]::SetEnvironmentVariable($valueName, 'true', 'Process')
        [Environment]::SetEnvironmentVariable($countName, [string]($configCount + 1), 'Process')
    }
    & $shorebirdCli @cliArguments
    if ($LASTEXITCODE -ne 0) { throw "Shorebird exited with code $LASTEXITCODE." }
} finally {
    if ($null -ne $savedGitEnvironment) {
        foreach ($name in $savedGitEnvironment.Keys) {
            if ($null -eq $savedGitEnvironment[$name]) {
                Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
            } else {
                [Environment]::SetEnvironmentVariable($name, $savedGitEnvironment[$name], 'Process')
            }
        }
    }
    Pop-Location
}
